package store

import "backend/model/home/job"

var JobsData = []job.Job{
	{
		Type:         "ad",
		Logo:         "images/safetywing.png",
		Title:        "Nomado Insurance by SafetyWing",
		Company:      "Remote OK • Full-time • $120k - $160k",
		MiddleBadges: []string{},
		ExtraBadges:  []string{},
		Time:         "Ad",
		ApplyLink:    "#",
		ApplyLabel:   "Sign up today",
	},
	{
		BadgeClass:    "title-verified",
		Type:          "verified",
		CardClass:     "verified collapsible-card",
		Logo:          "images/ecompany.jpg.png",
		Title:         "Junior Crypto Analyst & Trader",
		Company:       "ELEMENTAL TERRA",
		IsNew:         false,
		LocationBadge: "🌏 Worldwide",
		SalaryBadge:   "💰 $50k - $70k",
		TypeBadge:     "⏰ Part time",
		MiddleBadges:  []string{"other", "Crypto", "Finance"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi", "Edu", "Bitcoin", "Ethereum", "Legal"},
		Time:          "4d",
		IsPinned:      true,
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
		Detail: &job.JobDetail{
			HiringLabel: "ELEMENTAL TERRA is hiring a",
			RoleTitle:   "Remote Crypto Trader",
			Paragraphs: []string{
				"Elemental Terra is an international company working with digital assets, market research, and data-driven trading solutions. We are building a team of specialists who want to understand how crypto markets operate in practice and develop professional skills in a real market environment.",
				"We are opening a Crypto Trader position for candidates who are at the beginning of their professional journey and are interested in trading, market analysis, and data-driven decision-making. This role involves independent trading activity with structured training and ongoing support from experienced professionals. No prior professional experience is required - full training is provided.",
			},
			Responsibilities: []string{
				"Execute trades on digital asset markets using company strategies and guidelines.",
				"Monitor price movements, liquidity, and market conditions in real time.",
				"Analyze charts, indicators, and market signals to support trading decisions.",
				"Manage positions and assess potential risks.",
				"Review crypto news and its impact on market behavior.",
				"Work with professional trading platforms and analytical tools.",
				"Track and report personal trading performance.",
				"Continuously improve trading skills and market understanding.",
			},
			Offers: []string{
				"Opportunity to join an early-stage international company.",
				"Fully remote work - no location restrictions.",
				"Flexible workload and schedule.",
				"Structured onboarding and full training provided at the company's expense.",
				"Work on official, professional trading platforms.",
				"Step-by-step development with increasing responsibility.",
				"Continuous support from experienced market specialists.",
				"Compensation based on your trading performance and results.",
			},
			InterviewProcess: []string{
				"A scheduled phone call with our representative - we will contact you directly, so please be available to answer.",
				"Detailed interview with an HR manager.",
				"Practical training session with one of our trading specialists.",
			},
			InterviewNotice: "Please mention the word PRODUCTIVELY when applying to show you read the job post completely (#RNDkuMTU2LjQxLjIyMg==). This is a feature to avoid fake spam applicants. Companies can search these words to find applicants that read this and instantly see they're human.",
			Salary:          "$50,000 — $70,000/year",
			ApplyQuestion:   "How do you apply?",
			ApplyFormUrl:    "https://elementalterra.com/work/remote2",
			ApplyFormLabel:  "Apply for this job",
			Text:            "ELEMENTAL TERRA",
			Benefits:        []string{"⏰ Async", "🏖 Paid time off", "📆 4 day workweek", "📚 Learning budget", "🥧 Pay in crypto"},
			CompanyName:     "ELEMENTALTERRA",
			CompanyWebsite:  "https://elementalterra.com",
			CompanyLogo:     "./images/ecompany.jpg.png",
			QrCode:          "images/qrcode.png",
			QrLink:          "rok.co/ks",
			ApplyUrl:        "elementalterra.com",
		},
	},
	{
		BadgeClass:    "title-verified",
		Type:          "verified",
		Logo:          "images/gp_logo.png",
		Title:         "Senior Amazon Brand Manager 🎈",
		Company:       "GNO Partners",
		IsNew:         true,
		LocationBadge: "🌏 Worldwide",
		SalaryBadge:   "💰 $90k - $140k",
		MiddleBadges:  []string{"Sales", "Marketing", "Admin"},
		ExtraBadges:   []string{},
		Time:          "26d",
		IsPinned:      true,
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "highlight",
		CardClass:     "highlight-bg",
		Logo:          "images/a_company.jpg",
		Title:         "Senior Marketing Manager Paid Ads 🎈",
		Company:       "Acebet.com",
		IsNew:         false,
		LocationBadge: "🌏 Worldwide",
		SalaryBadge:   "💰 $50k - $70k",
		MiddleBadges:  []string{"Marketing"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "7d",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "./images/voxmedia.jpg",
		Title:         "Deputy Editor Future Perfect",
		Company:       "Vox Media, LLC",
		IsNew:         true,
		LocationBadge: "DC or NYC",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"Training", "Growth", "Lead"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "12h",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "images/cow_company.jpg",
		Title:         "Senior Marketing Manager Paid Ads",
		Company:       "Relativity Space",
		IsNew:         true,
		LocationBadge: "Long Beach, California",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"Technical", "Support", "Software"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "13h",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:      "promotion",
		Img:       "images/promotion.jpg",
		Title:     "Unlock Your Remote career potential with Remote OK Premium",
		Paragraph: "Get exclusive access and be the first to apply to 100,000+ remote jobs from 10,000+ top companies and land your dream remote position!",
		Rating:    "⭐️⭐️⭐️⭐️⭐ 4.8/5 from 10,000+ reviews ️",
		Button:    "Get instances acces",
	},
	{
		Type:          "standard",
		Logo:          "images/ecompany.jpg.png",
		Title:         "Lance Bridges Estimate and Quotation Company DBA Be",
		Company:       "ELEMENTAL TERRA",
		IsNew:         true,
		LocationBadge: "🌏 Worldwide",
		SalaryBadge:   "💰 $50k - $70k",
		TypeBadge:     "⏰ Part time",
		MiddleBadges:  []string{"Manager", "Technical", "Travel"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "5m",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "images/cow_company.jpg",
		Title:         "Senior IT Systems Engineer Storage and Infrastructu...",
		Company:       "Relativity Space",
		IsNew:         true,
		LocationBadge: "Long Beach, California",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"Technical", "Support", "Software"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "1d",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "images/logo-square.png",
		Title:         "Senior Backend Engineer Content",
		Company:       "onX",
		IsNew:         true,
		LocationBadge: "Bozeman",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"Content", "Senior", "Engineer"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "1d",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "images/image_001_560.png",
		Title:         "Senior Mobile iOS Engineer",
		Company:       "Yassir",
		IsNew:         true,
		LocationBadge: "🌏 Probably worldwide",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"iOS", "Design", "Redis"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "1d",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "images/image_002_6906.png",
		Title:         "Software Engineer UI",
		Company:       "Brave",
		IsNew:         true,
		LocationBadge: "Anywhere",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"Software", "UI", "Design"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "2d",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
	{
		Type:          "standard",
		Logo:          "images/image_003_2966.png",
		Title:         "Executive Assistant",
		Company:       "Wild Alaskan Company",
		IsNew:         false,
		LocationBadge: "🌏 Probably worldwide",
		SalaryBadge:   "💰 Upgrade to Premium to see salary",
		MiddleBadges:  []string{"Assistant", "Founder", "Executive"},
		ExtraBadges:   []string{"Web3", "Blockchain", "Defi"},
		Time:          "2d",
		ApplyLink:     "#",
		ApplyLabel:    "Apply now",
	},
}
